apiVersion: apps/v1
kind: Deployment
metadata:
  name: underlive-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: underlive-web
  template:
    metadata:
      labels:
        app: underlive-web
    spec:
      containers:
      - name: web-container
        image: 10.12.0.150/underlive/web:latest # 본인 하버 주소로 수정!
        ports:
        - containerPort: 80
