apiVersion: v1
kind: Service
metadata:
  name: underlive-web-service
spec:
  type: NodePort
  selector:
    app: underlive-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32405 # 비어있는 포트 아무거나 쓰셔도 됩니다.
